# -*- Ruby -*-

# for idnet(1)
CVS_ID = '$Id$'

LIB_DIR = File.join(File.dirname(__FILE__), '..', 'lib')
RCOV_DIR = File.join(File.dirname(__FILE__), 'coverage')

task :default => [ :test ]

task :test do
  ruby '-I', LIB_DIR, 'run.rb'
end

task :rcov do
  rm_rf RCOV_DIR
  sh 'rcov', '-I', LIB_DIR, 'run.rb'
end

task :clean do
  rm_rf RCOV_DIR
end

rule '.test' => [ '.rb' ] do |t|
  ruby t.source
end
