# -*- Ruby -*-

# for idnet(1)
CVS_ID = '$Id$'

LIB_DIR = File.join(File.dirname(__FILE__), '..', 'lib')

def run_ruby(*args)
  ruby '-I', LIB_DIR, *args
end

def run_rcov(*args)
  sh 'rcov', '-I', LIB_DIR, *args
end

task :default => [ :test ]

task :test do
  for unittest_rb in Dir['test_*.rb']
    run_ruby unittest_rb
  end
end

task :rcov do
  for unittest_rb in Dir['test_*.rb']
    run_rcov unittest_rb
  end
end

rule '.test' => [ '.rb' ] do |t|
  ruby t.source
end
